name: 'GitHub Actions XMU SIGN IN'

on:
  watch:
    types: started
  push:
  schedule:
    - cron: '05 23 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
#         - name: Random wait
           # You may pin to the exact commit or the version.
           # uses: m3y/random-wait-action@62e419c7545f204297b3d0f6d6b376e2256e2dfd
#           uses: m3y/random-wait-action@v1
#           with:
          # Maximum wait time
#             max-wait-time: 1800 # optional, default is 10
        - name: 'Checkout codes'
          uses: actions/checkout@v1
        - name: 'Set up Python'
          uses: actions/setup-python@v1
          with:
            python-version: '3.7'
        - name: 'Install requirements'
          run: |
            python -m pip install --upgrade pip
            pip install selenium
        - name: Install ChromeDriver
          run: |
            CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
              && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
              && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
              && cd /tmp \
              && unzip chromedriver_linux64.zip \
              && rm -rf chromedriver_linux64.zip \
              && sudo mv chromedriver /usr/local/bin/chromedriver \
              && sudo chmod +x /usr/local/bin/chromedriver \
              && chromedriver --version
#         - name: 'Get Date'
#           env:
#             REPORT_DATE: ${{ TZ=':Asia/Shenzhen' date '+%Y-%m-%d %T' }}
#           run: echo "Date is ${REPORT_DATE}"
        - name: 'AutoSignIn'
          env:
            XMU_USER: ${{ secrets.XMU_USER }}
            XMU_PASSWORD: ${{ secrets.XMU_PASSWORD }}
          run: python SignIn.py
